Job_ProtalBd/Models/Extended/Registration.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace Job_ProtalBd.Models
{
    [MetadataType(typeof(RegistrationMetadata))]
    public partial class Registration
    {
        public string ConfrimPassword { get; set; }
    }
    public class RegistrationMetadata
    {
        [Display(Name = "E_Mail")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " E_Mail Required")]
        [DataType(DataType.EmailAddress)]
        public string E_Mail { get; set; }

        [Display(Name = "First Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "First namerequired")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Last name required")]
        public string LastName { get; set; }

        [Display(Name = "State")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "The state required")]
        public string State { get; set; }

        [Display(Name = "City")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "The City required")]
        public string City { get; set; }

        [Display(Name = "Gender")]
       [Required(AllowEmptyStrings = false, ErrorMessage = "Gender required")]
        public string Gender { get; set; }

        [Display(Name = "Date Of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-mm-yyyy}")]
        public DateTime Date_Of_Birth { get; set; }

        [Display(Name = "Date Of Entry")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-mm-yyyy}")]
        public DateTime Date_Of_Entry { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = " Password Required")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "Minimum 4 characters number")]
        public string Password { get; set; }

        [Display(Name = "Confrim Pasword")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Do not match the password")]
        public string ConfrimPassword { get; set; }
    }
}

Job_ProtalBd/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Job_ProtalBd.Models
{
    public class Login
    {
        [Display(Name = "E_Mail Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " E_Mail  Id Required")]
        [DataType(DataType.EmailAddress)]
        public string E_Mail { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = " Password Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }

    }
}

Job_ProtalBd/Models/Registration.cs
namespace Job_ProtalBd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int UserId { get; set; }
        public string E_Mail { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public Nullable<System.DateTime> Date_Of_Entry { get; set; }
        public int Contact_Number { get; set; }
        public string Password { get; set; }
        public bool IsEmailVerried { get; set; }
        public System.Guid ActivationCode { get; set; }
    }
}

Job_ProtalBd/Controllers/SheekerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Job_ProtalBd.Models;
using System.IO;
using System.Net.Mail;
using System.Web.Security;
using System.Net;

namespace Job_ProtalBd.Controllers
{
    public class SheekerController : Controller
    {
        // GET: Registration1
        [HttpGet]
        public ActionResult Registration()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
         public ActionResult Registration([Bind(Exclude = "IsEmailVerried,ActivationCode")]Registration Registration)
        {
            bool Status = false;
            String message = "";
            
            // Mode validation
            if (ModelState.IsValid)
            {
                //email is alredey code
                var isExist = IsEmailExist(Registration.E_Mail);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "Email Already Exist");
                    return View(Registration);
                }
                //Genarete active code
              Registration.ActivationCode = Guid.NewGuid();

                //password hasshin
                Registration.Password = Crypto.Hash(Registration.Password);
                Registration.ConfrimPassword = Crypto.Hash(Registration.ConfrimPassword);

                Registration.IsEmailVerried = false;

                using (SheekerEntities1 dc = new SheekerEntities1())
                {
                    dc.Registrations.Add(Registration);
                    dc.SaveChanges();

             
                // SendVerificationLinkEmail(Registration.E_Mail,Registration.ActivationCode.ToString());
                    message = "Registration Sucessfully done.Account activication link" +
                              "has been send your email id:"+Registration.E_Mail;

                    Status = true;
                }
            }
            else
            {
                message = "Invalid Request";
            }
            //send user
            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View(Registration);
          }
        

        [HttpGet]
        public ActionResult VerifyAccount(string id)
        {
            bool Status = false;
            using(SheekerEntities1 dc =new SheekerEntities1())
            {
                dc.Configuration.ValidateOnSaveEnabled = false;
                var v = dc.Registrations.Where(a => a.ActivationCode == new Guid(id)).FirstOrDefault();
                if(v != null)
                {
                    v.IsEmailVerried = true;
                    dc.SaveChanges();
                    Status = true;
                }
                else
                {
                    ViewBag.Message = "Invalid Request";
                }
            }
            ViewBag.Status = Status;
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Login login, string ReturnUrl="")
        {
            string message = "";
            using(SheekerEntities1 dc = new SheekerEntities1())
            {
            var v=dc.Registrations.Where(a=>a.E_Mail==login.E_Mail).FirstOrDefault();
                if (v !=null)
                {
                    if (string.Compare(Crypto.Hash(login.Password),v.Password)==0)
                    {
                        int timeout = login.RememberMe ? 525600 : 20;
                        var ticket = new FormsAuthenticationTicket(login.E_Mail, login.RememberMe,timeout);
                        string encrypted = FormsAuthentication.Encrypt(ticket);
                        var cookise = new HttpCookie(FormsAuthentication.FormsCookieName,encrypted);

                        cookise.Expires = DateTime.Now.AddMinutes(timeout);
                        cookise.HttpOnly = true;
                        Response.Cookies.Add(cookise);

                        if (Url.IsLocalUrl(ReturnUrl))
                        {
                            return Redirect(ReturnUrl);

                        }
                        else
                        {
                            return RedirectToAction("Indo", "Home");
                        }
                    }
                    else
                    {
                        message = "InValid  provided";
                    }
                }
                else
                {
                    message = "InValid  provided";
                }
            }
             ViewBag.Message = message;
             return  View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult list()
        {
            var Registrations = new List<Registration>();
                using (SheekerEntities1 dc =new SheekerEntities1())
            {
                Registrations = dc.Registrations.ToList();

            }
            return View(Registrations);
        }
        public ActionResult Setting()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UploadResume()
        {
            return View();
        }
     
        [HttpPost]
        public ActionResult UploadResume(IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
            {
                string fil = Guid.NewGuid() +Path.GetExtension(file.FileName);
                file.SaveAs(Path.Combine(Server.MapPath("~/UploadResume"), fil));
                
            }
            return View("file uploaded successfully");
        }


        [NonAction]
        public bool IsEmailExist(string E_Mail)
        {
            using (SheekerEntities1 dc = new SheekerEntities1())
            {
                Registration v = dc.Registrations.Where(a => a.E_Mail == E_Mail).FirstOrDefault();
                return v != null;
            }
            
        }
       /*[NonAction]
        public void SendVerificationLinkEmail(string E_Mail, string ActivationCode)
        {
            var scheme = Request.Url.Scheme;
            var host = Request.Url.Host;
            var port = Request.Url.Port;

            string url = scheme + "://" + host;

            var verifyUrl = "//" + ActivationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            var fromEmail = new MailAddress("jobportalbd@gmail.com", "Dotnet Awesome");
            var toEmail = new MailAddress(E_Mail);
            var fromEmailPassword = "********"; // Replace with actual password
            string subject = "Your account is successfully created!";

            string body = "<br/><br/>We are excited to tell you that your Dotnet Awesome account is" +
                " successfully created. Please click on the below link to verify your account" +
                " <br/><br/><a href='" + link + "'>" + link + "</a> ";

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
        }*/

    }
}

Job_ProtalBd/Views/Sheeker/Login.cshtml
@model Job_ProtalBd.Models.Login

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_MasterHome.cshtml";
}

<h2 style="text-align:center">Login From</h2>
@Styles.Render("~/Content/Sheeker/Login.css")
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
<div>
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.E_Mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.E_Mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.E_Mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RememberMe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.RememberMe)
                    @Html.ValidationMessageFor(model => model.RememberMe, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Job_ProtalBd/Views/Sheeker/Registration.cshtml
@model Job_ProtalBd.Models.Registration
@Styles.Render("Content/Sheeker/Registration.css")

@{

    Layout = "~/Views/Shared/_MasterHome.cshtml";
}
<h2 style="text-align:center"> Job Sheeker Registration</h2>
@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-success">
            <strong>Success !</strong>@ViewBag.Message
        </div>
    }

}
else

{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Styles.Render("~/Content/Sheeker/Registration.css")
        <div class="menu">
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.E_Mail, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.E_Mail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.E_Mail, "", new { @class = "text-danger" })
                        @Html.ValidationMessage("EmailExist", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date_Of_Birth, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date_Of_Entry, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date_Of_Entry, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date_Of_Entry, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Contact_Number, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Contact_Number, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Contact_Number, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ConfrimPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ConfrimPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ConfrimPassword, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
        if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                <strong>Error !</strong>@ViewBag.Message
            </div>
        }
    }
}
@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

}

Job_ProtalBd/Views/Sheeker/Setting.cshtml
@{
    ViewBag.Title = "Setting";
    Layout = "~/Views/Shared/_SheekerMaster.cshtml";
    @Styles.Render("~/Content/Sheeker/Setting.css")
}
<div class="setting">
    <h2><b>Account Setting</b></h2>
    <p>Here you will be able to change your password, resume privacy, notification settings, delete resume, delete account and set / change User ID at any time.</p>
    <div class="delete" onclick=""><ul><li class="uli">@Html.ActionLink("Change Password", "About", "Home")</li></ul></div>
    <div class="email" onclick=""><ul><li class="uli">@Html.ActionLink(" Email Notification", "About", "Home")</li></ul></div>
    <div class="deleteacc" onclick=""><ul><li class="uli">@Html.ActionLink("Delete Account", "About", "Home")</li></ul></div>
    <div class="deleteres" onclick=""><ul><li class="uli">@Html.ActionLink(" Delete Resume", "About", "Home")</li></ul></div>
    <div class="userchange" onclick=""><ul><li class="uli">@Html.ActionLink("Use/Id Change", "About", "Home")</li></ul></div>
</div>

Job_ProtalBd/Views/Sheeker/UploadResume.cshtml
@{
    ViewBag.Title = "UploadResume";
    Layout = "~/Views/Shared/_SheekerMaster.cshtml";
}
<DOCTYPE html>
    <html>
    <head>
        <title></title>
    </head>
    <body>
        @using (Html.BeginForm("UploadResume", "Sheeker", FormMethod.Post, new { enctype="multipart/from-data"}))
        {
            <table>
                <tr>
                    <td> Photo</td>
                    <td> <input  type="file" name=" photo"/></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td><input  type="button" value="Submit"/></td>
                </tr>
            </table>
        }

    </body>
</html>

Job_ProtalBd/Views/Sheeker/VerifyAccount.cshtml
@{
    ViewBag.Title = "VerifyAccount";
    Layout = "~/Views/Shared/_Master.cshtml";
}

<h2>VerifyAccount</h2>
@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-success">
            <strong>Success !</strong>Your Account has been activated succesfully.Click hear to @Html.ActionLink("Login","LoginorRegistration","Home");
        </div>
    }
   else
    {
        <div class="alert alert-danger">
            <strong>Error ! </strong>@ViewBag.Message
        </div>
    }
}

Job_ProtalBd/Views/Sheeker/list.cshtml
@{
    Layout = null;
}
@{ 
    ViewBag.Title = "Job Sheeker List";
    var gird = new WebGrid(source: Model, canPage: true, rowsPerPage: 10);
    gird.Pager(WebGridPagerModes.All);
}
<h2> List Of  Job Sheeker </h2>
<style type="text/css">
    .webgrid-table {
        font-family: "Trebuchet MS",Arial,sans-serif;
        font-size: 12px;
        width: 100%;
        display: table;
        border-collapse: separate;
        border: solid 1px #988f21;
        background-color: white;
    }

        .webgrid-table td, th {
            border: 1px solid #988f21;
            padding:15px;
        }

    .webgrid-header {
        background-color: #A7C942;
        color: #FFFFFF;
        padding-bottom: 4px;
        padding-top: 5px;
        text-align: left;
    }

    .webgrid-footer {
    }

    .webgrid-row-style {
        padding: 15px;
    }

    .webgrid-alternating-row {
        background-color: #FAF2D3;
        padding: 3px 7px 2px;
    }
</style>
<div id="content">
    @gird.GetHtml(

    tableStyle: "webgrid-table",
    headerStyle: "webgrid-header",
    footerStyle: "webgrid-footer",
    alternatingRowStyle: "webgrid-alternating-row",
    rowStyle: "webgrid-row-style",
    columns:gird.Columns(
        gird.Column(columnName: "UserId", header: "UserId"),
        gird.Column(columnName: "FirstName", header: "FirstName"),
        gird.Column(columnName: "LastName", header: "LastName"),
        gird.Column(columnName: "State", header: "State"),
        gird.Column(columnName: "City", header: "City"),
        gird.Column(columnName: "Gender", header: "Gender"),
        gird.Column(columnName: "Password", header: "Password")




        ))

</div>